# SQL Interview Practice – Real Business Analyst Workflow

This notebook is a practical SQL interview review using retail datasets.

The aim is to practise SQL through realistic business questions, similar to how a Data Analyst or Business Analyst would explore customer, order, and product data.

The CSV files used in this project are:
- `customers (1).csv`
- `orders (1).csv`
- `products (1).csv`

# Step 1 — Importing Pandas

In [2]:
import pandas as pd

# Step 2 — Loading the CSV Datasets

In [3]:
customers = pd.read_csv("customers (1).csv")
orders = pd.read_csv("orders (1).csv")
products = pd.read_csv("products (1).csv")

# Step 3 — Exploring the Customers Dataset

In [4]:
customers.head()

  customer_id  gender  age        city signup_date loyalty_member
0       C0001    Male   19   Liverpool  2023-10-17            Yes
1       C0002    Male   65  Manchester  2022-08-17            Yes
2       C0003  Female   20      London  2023-08-28            Yes
3       C0004    Male   50      London  2022-08-12            Yes
4       C0005  Female   32  Nottingham  2023-10-28             No

# Step 4 — Exploring the Orders Dataset

In [5]:
orders.head()

  order_id customer_id product_id  order_date  quantity payment_method
0   O00001       C0692       P006  2023-01-29         4           Card
1   O00002       C1072       P059  2023-04-19         5           Card
2   O00003       C1187       P030  2024-01-15         1           Card
3   O00004       C0290       P063  2024-01-12         1           Cash
4   O00005       C0094       P032  2024-04-09         2           Card

# Step 5 — Exploring the Products Dataset

In [6]:
products.head()

  product_id    product_name category   price
0       P001       Blender 1   Beauty  272.76
1       P002       Perfume 2     Home  132.09
2       P003  Water Bottle 3     Home   58.58
3       P004   Smart Watch 4     Home  220.82
4       P005       Perfume 5     Home   27.81

# Step 6 — Checking Basic Data Quality and Summary Statistics

In [7]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     1200 non-null   object
 1   gender          1200 non-null   object
 2   age             1200 non-null   int64
 3   city            1200 non-null   object
 4   signup_date     1200 non-null   object
 5   loyalty_member  1200 non-null   object
dtypes: int64(1), object(5)
memory usage: 56.4+ KB

In [8]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        4000 non-null   object
 1   customer_id     4000 non-null   object
 2   product_id      4000 non-null   object
 3   order_date      4000 non-null   object
 4   quantity        4000 non-null   int64
 5   payment_method  4000 non-null   object
dtypes: int64(1), object(5)
memory usage: 187.6+ KB

In [9]:
orders.describe()

          quantity
count  4000.000000
mean      2.974750
std       1.411599
min       1.000000
25%       2.000000
50%       3.000000
75%       4.000000
max       5.000000

In [10]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    80 non-null     object
 1   product_name  80 non-null     object
 2   category      80 non-null     object
 3   price         80 non-null     float64
dtypes: float64(1), object(3)
memory usage: 2.6+ KB

In [11]:
customers.isnull().sum()

customer_id       0
gender            0
age               0
city              0
signup_date       0
loyalty_member    0
dtype: int64

In [12]:
orders.isnull().sum()

order_id          0
customer_id       0
product_id        0
order_date        0
quantity          0
payment_method    0
dtype: int64

In [13]:
products.isnull().sum()

product_id      0
product_name    0
category        0
price           0
dtype: int64

In [14]:
customers.describe()

               age
count  1200.000000
mean     41.615833
std      13.719515
min      18.000000
25%      30.000000
50%      41.000000
75%      54.000000
max      65.000000

In [15]:
products.describe()

            price
count   80.000000
mean   140.082875
std     87.534130
min     11.070000
25%     58.922500
50%    126.115000
75%    214.132500
max    289.840000

# Step 7 — Importing SQLite

In [16]:
import sqlite3

# Step 8 — Creating the SQLite Database Connection

In [17]:
conn = sqlite3.connect("retail busienss.db")

# Step 9 — Converting DataFrames into SQL Tables

In [18]:
orders.to_sql("orders", conn, if_exists = "replace" , index = False)

4000

In [19]:
products.to_sql("products", conn, if_exists = "replace" , index= False)

80

In [20]:
customers.to_sql("customers", conn, if_exists= "replace" , index= False)

1200

# Step 10 — Running the First SQL Query

In [21]:
query = """
SELECT *
From customers
"""

pd.read_sql(query, conn)

     customer_id  gender  age        city signup_date loyalty_member
0          C0001    Male   19   Liverpool  2023-10-17            Yes
1          C0002    Male   65  Manchester  2022-08-17            Yes
2          C0003  Female   20      London  2023-08-28            Yes
3          C0004    Male   50      London  2022-08-12            Yes
4          C0005  Female   32  Nottingham  2023-10-28             No
...          ...     ...  ...         ...         ...            ...
1195       C1196  Female   20      London  2023-02-25             No
1196       C1197    Male   55  Nottingham  2023-01-13            Yes
1197       C1198  Female   47  Manchester  2022-05-26            Yes
1198       C1199  Female   58  Manchester  2022-09-09             No
1199       C1200    Male   39      London  2023-09-20             No

[1200 rows x 6 columns]

In [22]:
query = """
select *
from orders
"""

pd.read_sql(query,conn)

     order_id customer_id product_id  order_date  quantity payment_method
0      O00001       C0692       P006  2023-01-29         4           Card
1      O00002       C1072       P059  2023-04-19         5           Card
2      O00003       C1187       P030  2024-01-15         1           Card
3      O00004       C0290       P063  2024-01-12         1           Cash
4      O00005       C0094       P032  2024-04-09         2           Card
...       ...         ...        ...         ...       ...            ...
3995   O03996       C1004       P055  2024-03-30         5           Card
3996   O03997       C1008       P014  2024-05-10         4           Card
3997   O03998       C0604       P021  2023-01-30         5         Online
3998   O03999       C0234       P037  2023-07-10         3         Online
3999   O04000       C1182       P071  2023-07-26         2           Card

[4000 rows x 6 columns]

In [23]:
query = """
select *
from customers
"""
pd.read_sql(query,conn)

     customer_id  gender  age        city signup_date loyalty_member
0          C0001    Male   19   Liverpool  2023-10-17            Yes
1          C0002    Male   65  Manchester  2022-08-17            Yes
2          C0003  Female   20      London  2023-08-28            Yes
3          C0004    Male   50      London  2022-08-12            Yes
4          C0005  Female   32  Nottingham  2023-10-28             No
...          ...     ...  ...         ...         ...            ...
1195       C1196  Female   20      London  2023-02-25             No
1196       C1197    Male   55  Nottingham  2023-01-13            Yes
1197       C1198  Female   47  Manchester  2022-05-26            Yes
1198       C1199  Female   58  Manchester  2022-09-09             No
1199       C1200    Male   39      London  2023-09-20             No

[1200 rows x 6 columns]

# Step 12 — Aggregating Customers by City Using GROUP BY

“We are planning a new marketing campaign. I want to know how many customers we have in each city.”

In [24]:
query = """
SELECT city,count(customer_id) as cnt
FROM customers
group by city
order by cnt desc

"""

pd.read_sql(query,conn)

         city  cnt
0   Sheffield  163
1  Nottingham  160
2  Birmingham  159
3     Bristol  156
4      London  146
5       Leeds  146
6   Liverpool  137
7  Manchester  133

"We need the table which can see the orders and cutomers to gether with any information we have about them"

In [26]:
query = """
SELECT *
FROM orders
LEFT JOIN customers
on customers.customer_id = orders.customer_id 

"""

pd.read_sql(query, conn)

,order_id,customer_id,product_id,order_date,quantity,payment_method,customer_id,gender,age,city,signup_date,loyalty_member
0,O00001,C0692,P006,2023-01-29,4,Card,C0692,Male,46,London,2023-01-14,No
1,O00002,C1072,P059,2023-04-19,5,Card,C1072,Male,50,Nottingham,2022-07-10,Yes
2,O00003,C1187,P030,2024-01-15,1,Card,C1187,Male,48,Birmingham,2023-11-10,Yes
3,O00004,C0290,P063,2024-01-12,1,Cash,C0290,Female,39,London,2023-02-01,No
4,O00005,C0094,P032,2024-04-09,2,Card,C0094,Male,36,Bristol,2023-11-06,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...
3995,O03996,C1004,P055,2024-03-30,5,Card,C1004,Male,28,Nottingham,2022-04-02,Yes
3996,O03997,C1008,P014,2024-05-10,4,Card,C1008,Male,62,Sheffield,2022-07-17,No
3997,O03998,C0604,P021,2023-01-30,5,Online,C0604,Male,49,Bristol,2022-01-12,No
3998,O03999,C0234,P037,2023-07-10,3,Online,C0234,Female,19,Birmingham,2022-09-01,No
3999,O04000,C1182,P071,2023-07-26,2,Card,C1182,Male,57,Sheffield,2023-08-20,Yes

# Step 13 — Joining Customers and Orders to Analyse Loyalty Members

“I want to know whether loyalty members are generating more orders.”

In [27]:
query = """
SELECT loyalty_member,
    count(order_id)
FROM orders
LEFT JOIN customers
ON orders.customer_id = customers.customer_id
group by loyalty_member 
order by loyalty_member desc
"""

pd.read_sql(query, conn)

  loyalty_member  count(order_id)
0            Yes             1906
1             No             2094

In [28]:
query = """
SELECT *
FROM customers
WHERE loyalty_member = "Yes" 
and city = "London"
"""

pd.read_sql(query, conn)

   customer_id  gender  age    city signup_date loyalty_member
0        C0003  Female   20  London  2023-08-28            Yes
1        C0004    Male   50  London  2022-08-12            Yes
2        C0022  Female   23  London  2023-06-06            Yes
3        C0047    Male   21  London  2023-07-18            Yes
4        C0075    Male   44  London  2022-06-16            Yes
..         ...     ...  ...     ...         ...            ...
61       C1103  Female   46  London  2023-02-28            Yes
62       C1144    Male   41  London  2022-06-29            Yes
63       C1178    Male   26  London  2022-04-03            Yes
64       C1183    Male   41  London  2022-10-29            Yes
65       C1189    Male   26  London  2022-10-23            Yes

[66 rows x 6 columns]

# Step 14 — Revenue Analysis Using SUM and AVG

“Which product categories generate the highest revenue?”

In [29]:
query = """
SELECT category,
    AVG(price) AS AvgPrice ,
    SUM(quantity) AS TotalNumber, 
    SUM(price*quantity) AS TotalPay
FROM orders
LEFT JOIN products
ON orders.product_id = products.product_id
GROUP BY category
ORDER BY TotalPay desc
"""

pd.read_sql(query,conn)

      category    AvgPrice  TotalNumber   TotalPay
0         Home  156.160939         3074  473002.14
1       Sports  125.042247         3250  403963.89
2     Clothing  152.295859         2101  319942.70
3       Beauty  147.178077         1623  239438.96
4  Electronics  115.375579         1851  208470.02

“Show me only product categories that generated more than £300,000 revenue.”

In [30]:
query = """
SELECT 
    category AS Category,
    SUM((price*quantity)) AS TotalPay,
    AVG(price) AS AvgPrice,
    SUM(quantity) AS TotalNum
FROM orders
LEFT JOIN products
ON products.product_id = orders.product_id
GROUP BY category
HAVING Totalpay >= 300000
ORDER BY TotalPay desc
"""

pd.read_sql(query, conn)

   Category   TotalPay    AvgPrice  TotalNum
0      Home  473002.14  156.160939      3074
1    Sports  403963.89  125.042247      3250
2  Clothing  319942.70  152.295859      2101

In [31]:
query = """
SELECT *
FROM customers
"""

pd.read_sql(query, conn)

     customer_id  gender  age        city signup_date loyalty_member
0          C0001    Male   19   Liverpool  2023-10-17            Yes
1          C0002    Male   65  Manchester  2022-08-17            Yes
2          C0003  Female   20      London  2023-08-28            Yes
3          C0004    Male   50      London  2022-08-12            Yes
4          C0005  Female   32  Nottingham  2023-10-28             No
...          ...     ...  ...         ...         ...            ...
1195       C1196  Female   20      London  2023-02-25             No
1196       C1197    Male   55  Nottingham  2023-01-13            Yes
1197       C1198  Female   47  Manchester  2022-05-26            Yes
1198       C1199  Female   58  Manchester  2022-09-09             No
1199       C1200    Male   39      London  2023-09-20             No

[1200 rows x 6 columns]

# Step 16 — Customer Segmentation Using CASE WHEN

“Segment customers by age group.”

In [32]:
query = """
SELECT 
    *,
    CASE   
    WHEN age<30 THEN "Young"
    WHEN age between 30 and 50 THEN "Adult"
    WHEN age> 50 THEN "Senior"
    END AS Segmentation
FROM customers

"""

pd.read_sql(query, conn)

,customer_id,gender,age,city,signup_date,loyalty_member,Segmentation
0,C0001,Male,19,Liverpool,2023-10-17,Yes,Young
1,C0002,Male,65,Manchester,2022-08-17,Yes,Senior
2,C0003,Female,20,London,2023-08-28,Yes,Young
3,C0004,Male,50,London,2022-08-12,Yes,Adult
4,C0005,Female,32,Nottingham,2023-10-28,No,Adult
...,...,...,...,...,...,...,...
1195,C1196,Female,20,London,2023-02-25,No,Young
1196,C1197,Male,55,Nottingham,2023-01-13,Yes,Senior
1197,C1198,Female,47,Manchester,2022-05-26,Yes,Adult
1198,C1199,Female,58,Manchester,2022-09-09,No,Senior
1199,C1200,Male,39,London,2023-09-20,No,Adult

# Final Business Insights

This practice reviewed key SQL interview topics through business-focused questions:

- Filtering customers using `WHERE`
- Counting and grouping customers with `GROUP BY`
- Joining tables using `LEFT JOIN`
- Calculating revenue with `SUM(price * quantity)`
- Filtering aggregated results using `HAVING`
- Creating customer segments using `CASE WHEN`

This workflow connects SQL syntax with real analytical thinking, which is useful for Data Analyst, Business Analyst, and graduate analytics interviews.